name: thoth

services:
  thoth:
    build: .
    image: thoth
    container_name: thoth
    volumes:
      - ./wapps/thoth:/thoth
    ports:
      - "8054:8080"
    networks:
      - textailes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thoth.rule=Host(`thoth.textailes.athenarc.gr`)"
      - "traefik.http.routers.thoth.entrypoints=websecure"
      - "traefik.http.routers.thoth.tls.certresolver=le"
    restart: "always"

networks:
  textailes:
    external: true