name: thoth

services:
  thoth:
    build: .
    image: thoth
    container_name: thoth
    ports:
      - "8054:8080"
    environment:
      THOTH_DEPLOYMENT_MODE: local
    volumes:
      - aton-data:/aton/data
      - aton-config:/aton/config
    networks:
      - thoth-local
    restart: unless-stopped

networks:
  thoth-local:
    driver: bridge

volumes:
  aton-data:
  aton-config:
